version: 2
models:
  - name: dim_customers
    description: one record per customer
    columns:
      - name: customer_id
        description: primary key
        tests:
          - unique
          - not_null
      - name: first_order_date
        description: NULL when a customer has not yet placed an order.
  - name: fct_orders
    description: fact orders. one record for each transaction (order)
    access: protected
    latest_version: 1
    config:
      group: finance
      contract:
        enforced: true
    columns:
      - name: order_id
        data_type: varchar
        constraints:
          - type: not_null
      - name: customer_id
        data_type: varchar
        tests:
          - not_null
      - name: order_date
        data_type: date
      - name: amount
        description: dollars spent per order
        data_type: number
        tests:
          - average_dollars_spent_greater_than_one :
              group_by_column: "customer_id"
          - dbt_expectations.expect_column_values_to_be_between :
              #this will perform what the dbt_utils.expression-is-true test does!
              min_value : 0
              row_condition : "order_id is not null"
              strictly : false
    versions:
      - v: 1
        config:
          alias: fct_orders
      - v: 2
        columns:
          - name: location_ordered_at
            data_type: date
          - name: order_amount
            data_type: number
          - exclude: 
            - order_date
            - amount
            include: all
          
  - name: fct_customer_orders
    description: fact customer orders